### ISSUE TITLE
Make it demo-able

### ISSUE THREAD

**Issue by hmil** [vaultage-pm/vaultage#160]
The demo that showcased v1 was cool. Add features to make it easy to deploy a demo.

It could be a `--demo` flag which runs the server in a special mode with the following characteristics:
- prevent changing the master password
- create a predefined user and password
- (maybe: do not use disk storage)

Deploy in docker with:
```
docker run -d --init -p $PORT:3000 --name vaultage-demo --restart always hmil/vaultage vaultage-server --demo
```

Then set a cron job to restart the demo every day:
```
docker stop vaultage-demo

# The following two steps are only needed if the demo persists to disk:
docker remove valutage-demo
docker run -d --init -p $PORT:3000 --name vaultage-demo --restart always hmil/vaultage vaultage-server --demo

docker start vaultage-demo
```

**Comment by lbarman** [comment]
Done https://github.com/vaultage-pm/vaultage/pull/201
I didn't use a CRON, I just made that the changes are never pushed to the server. The UI still behaves mostly the same (but loses all changes when the window is closed).
