### ISSUE TITLE
Move out of sjcl

### ISSUE THREAD

**Issue by hmil** [vaultage-pm/vaultage#184]
There are a few issues with our reliance on sjcl:

- The lib is a compact piece of JS fished in the internet, not actively audited nor maintained
- We rely on its obscure format for serialization and deserialization (hence we do not control the actual format we store!)
- It is slow on mobile (see https://github.com/vaultage-pm/vaultage-mobile/issues/2 )

Proposal:
- create a crypto interface exposing the cryptographic primitives we need
- create an interface to accurately model the cipher format

The `vaultage-client` library should still work out of the box in any JS environment. I see a couple ways to achieve this:
1. provide a default JS crypto implementation and offer an API to inject a custom crypto implementation. Applications use this interface to provide access to an accelerated crypto.
2. develop multiple implementations in this repo and detect the environment at run-time to pick which implementation gets used.

**1** is more flexible but complicates the API. Besides, apps which are not using the default crypto still ship it as dead code.
**2** is simpler to use but may make the library heavier because we need to ship all implementations. Besides, manual steps might still be required to have the library bind to the desired primitives.

Enablers:
The crypto primitives we use (true randomness, pbkdf2, sha256, AES_ccm) are well known and available in various libraries in many environments (eg: [node](https://nodejs.org/api/crypto.html), [browser](https://github.com/crypto-browserify/crypto-browserify), [rn partial port](https://www.npmjs.com/package/react-native-crypto), [rn pbkdf2](https://github.com/Airbitz/react-native-fast-crypto))
We can actually compare the result of each implementation and verify that they match.

Misc:
- We will need migration code to convert old ciphers to the new format
- The crypto API needs to be asynchronous because environments such as React Native can only asynchronously talk to native code

**Comment by lbarman** [comment]
Update: it seems like the way to go is OpenPGP.js, which is used and maintained by ProtonMail

https://github.com/openpgpjs/openpgpjs

**Comment by hmil** [comment]
It might be a good idea to merge #186 first. This allows us to add another crypto backend without disrupting the other implementations, and make sure that the new implementation is backward-compatible (exact format of IVs, keys, etc...)

**Comment by lbarman** [comment]
It would be nice; I didn't know if this was ready or not.

Realistically, we won't be supporting various cryptographic librairies & suites, even on bigger project, that's a "feature" which is used rarely. But if the cost of making a clean abstraction is not too high, why not, especially if we have to do the work anyway for OpenPGP.js

**Comment by hmil** [comment]
Crypto interface was abstracted away. vaultage-client now ships with two bundles for browser and node targets
- Browser bundle: uses sjcl
- nodejs bundle: uses [node crypto](https://nodejs.org/docs/latest-v12.x/api/crypto.html) primitive.

Packaging is not yet fully figured out (eg. what if I want to _bring my own_ crypto) but that's a first step.
