### ISSUE TITLE
Escaped html string in web-cli

### ISSUE THREAD

**Issue by lbarman** [vaultage-pm/vaultage#199]
``` <td class="reuse">(warning: re-used 1 times)</td> <td class="reuse">(warning: re-used 1 times)</td>``` appears sometime

**Comment by hmil** [comment]
https://github.com/vaultage-pm/vaultage/blob/master/packages/vaultage-ui-webcli/src/VaultEntryFormatter.ts#L97
☝️ the template literal is missing the `html` prefix to indicate that it contains safe html
