### ISSUE TITLE
Only show the first 10 results

### ISSUE THREAD

**Issue by lbarman** [vaultage-pm/vaultage#205]

**Comment by hmil** [comment]
Dafuq?

**Comment by lbarman** [comment]
C'est hyper relou de chercher "address@gmail.com" pour trouver le password de mon compte junk mail, et d'avoir 250 résultats qui arrivent et qui scrollent. D'autant plus qu'on a toujours le fait que sélectionner un texte redonne le focus tout en bas du scroll. Je voulais mettre une config user "max_results" qui tronque les résultats et affiche [... X more results, click here or refine your search]

**Comment by lbarman** [comment]
Done https://github.com/vaultage-pm/vaultage/pull/207/commits/6ca93c1ae1b869c051e5dbcfec84037c129c79e0
